//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssueStaff
    {
        public string TransactionID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string AccessionNo { get; set; }
        public string StaffID { get; set; }
        public string Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
