//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseFee
    {
        public int Id { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<double> Fee { get; set; }
        public string Month { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Fee Fee1 { get; set; }
    }
}
