//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.BookIssueStaffs = new HashSet<BookIssueStaff>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string DOB { get; set; }
        public string PermanentAddress { get; set; }
        public string TemporaryAddress { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string DateOfJoining { get; set; }
        public string Qualification { get; set; }
        public string YearOfExperience { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public byte[] Picture { get; set; }
        public string Status { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookIssueStaff> BookIssueStaffs { get; set; }
    }
}
