//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string StartingDate { get; set; }
        public string StartingTime { get; set; }
        public string EndingDate { get; set; }
        public string EndingTime { get; set; }
        public string ManagedBy { get; set; }
        public string Activities { get; set; }
    }
}
