//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public string Grade1 { get; set; }
        public Nullable<decimal> ScoreFrom { get; set; }
        public Nullable<decimal> ScoreTo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> GradePoint { get; set; }
    }
}
