//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelFeePayment
    {
        public string HFeePaymentID { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<int> TotalPaid { get; set; }
        public string ModeOfPayment { get; set; }
        public string PaymentModeDetails { get; set; }
        public Nullable<int> Fine { get; set; }
        public Nullable<int> DueFees { get; set; }
        public string Dateofpayment { get; set; }
        public Nullable<int> HostelFees { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
