//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracADOWeb.Models.DBModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public int ScholarshipID { get; set; }
        public string ScholarshipName { get; set; }
        public string Description { get; set; }
        public string Amount { get; set; }
    }
}
